name: foresight-maven-build-lab

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
    
  workflow_dispatch:

env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.me
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.me

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY_LAB }}
      
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          
      - name: Run Gradle Tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check 
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

